# Training and testing model

In [1]:
import sys
sys.path.append("/Users/synneeikeland/Documents/ML_course/ML4Physics_homework3/rl-ion-trap-tutorial")

print(sys.path)


['/Users/synneeikeland/Documents/ML_course/ML4Physics_homework3', '/opt/homebrew/Cellar/python@3.11/3.11.9/Frameworks/Python.framework/Versions/3.11/lib/python311.zip', '/opt/homebrew/Cellar/python@3.11/3.11.9/Frameworks/Python.framework/Versions/3.11/lib/python3.11', '/opt/homebrew/Cellar/python@3.11/3.11.9/Frameworks/Python.framework/Versions/3.11/lib/python3.11/lib-dynload', '', '/Users/synneeikeland/Library/Python/3.11/lib/python/site-packages', '/opt/homebrew/lib/python3.11/site-packages', '/Users/synneeikeland/Documents/ML_course/Machine-Learning-Course', '/Users/synneeikeland/Documents/ML_course/ML4Physics_homework3/rl-ion-trap-tutorial']


In [2]:
# check if ion_trap is correctly installed

from ion_trap import IonTrapEnv
env = IonTrapEnv(num_ions=3)
print(env.num_actions)

19


In [3]:
# Test environment

from ion_trap import IonTrapEnv
import numpy as np

env = IonTrapEnv(
    phases={'pulse_angles':[np.pi/2],
            'pulse_phases':[np.pi/2],
            'ms_phases':[-np.pi/2]},
    num_ions=3,
    goal=[[1,1,1]]
)

print("num_actions =", env.num_actions)


num_actions = 7


In [4]:
# Train RL model

!python3.11 train.py

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.
/opt/homebrew/lib/python3.11/site-packages/stable_baselines3/common/vec_env/patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(
Using cpu device
/opt/homebrew/lib/python3.11/site-packages/stable_baselines3/common/policies.py:486: UserWarning: As shared layers in the mlp_extra

In [5]:
# Evaluate trained model

from model import model
import torch
from utils import valid_srvs

agent = model()
samples = torch.tensor(valid_srvs)
preds = agent.pred(samples)

for srv, pred in zip(valid_srvs, preds):
    print(srv, pred.tolist())


Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.


[1 1 1] [0, 3, 0, 0, 0, 0, 0, 0, 0, 0]
[1 2 2] [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[2 1 2] [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[2 2 1] [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[2 2 2] [0]
[2 2 3] [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[2 3 2] [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[2 3 3] [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[3 2 2] [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[3 2 3] [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[3 3 2] [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[3 3 3] [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
